{{- $components := list
(dict "name" "api" "config" .Values.api.serviceAccount)
(dict "name" "worker" "config" .Values.worker.serviceAccount)
(dict "name" "subtask-worker" "config" .Values.subtaskWorker.serviceAccount)
(dict "name" "model-service" "config" .Values.modelService.serviceAccount)
(dict "name" "frontend" "config" .Values.frontend.serviceAccount)
(dict "name" "analysis-toolkit" "config" .Values.analysisToolkit.serviceAccount)
(dict "name" "data-ingestor" "config" .Values.dataIngestor.serviceAccount)
(dict "name" "migrations" "config" .Values.migrations.serviceAccount)
(dict "name" "queue-service" "config" .Values.queue.serviceAccount)
-}}
{{- range $components }}
  {{- if .config.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ragnerock.serviceAccountName" (dict "context" $ "config" .config "component" .name) }}
  labels:
    {{- include "ragnerock.labels" $ | nindent 4 }}
    {{- include "ragnerock.selectorLabels" (dict "context" $ "component" .name) | nindent 4 }}
    {{- with .config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
